### PR TITLE
Consider header rate limit information for getRateLimit()

### LINKED ISSUE #802: getRateLimit() ignores header rate limit
**Describe the bug**
I use a GitHub Enterprise instance that does not support the `/rate_limit` endpoint (it returns a 404 error) but it _does_ return `X-RateLimit` headers.

`org.kohsuke.github.GitHubClient#getRateLimit` only checks the `/rate_limit` endpoint, and thus returns an "unknown" rate limit in this case, even though there is a configured rate limit, causing the client to potentially exceed that limit.

To add insult to injury, on our GHE instance calls to `/rate_limit` count against our rate limit, so we exceed the limit that much faster. 😄 I believe there are plans to address this, but I don't know the timeframe.

**Expected behavior**
`org.kohsuke.github.GitHubClient#getRateLimit` should return valid rate limit information if the server supports either the `/rate-limit` endpoint or the `X-RateLimit` headers.

Ideally the client would cache the knowledge of whether the `/rate_limit` endpoint is available, and fall back to exclusively using the headers in this case.

### PR DESCRIPTION
**Pull request by bitwiseman**
# Description 
When `getRateLimit()` call gets a 404 response, use the header rate limit information if it is available.  

Fixes #802

@timja Could you take a look at this? 

# Before submitting a PR:
We love getting PRs, but we hate asking people for the same basic changes every time. 

- [x] Push your changes to a branch other than `master`. Create your PR from that branch.    
- [x] Add JavaDocs and other comments
- [x] Write tests that run and pass in CI. See [CONTRIBUTING.md](CONTRIBUTING.md) for details on how to capture snapshot data.
- [x] Run `mvn clean compile` locally. This may reformat your code, commit those changes.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.

### CODE REVIEW

File: src/main/java/org/kohsuke/github/GitHubClient.java [hunk 1]
```diff
@@ -210,21 +210,31 @@ public boolean isAnonymous() {
...
-        GHRateLimit rateLimit;
+        GHRateLimit result;
         try {
-            rateLimit = fetch(JsonRateLimit.class, "/rate_limit").resources;
+            result = fetch(JsonRateLimit.class, "/rate_limit").resources;
         } catch (FileNotFoundException e) {
-            // GitHub Enterprise doesn't have the rate limit
-            // return a default rate limit that
-            rateLimit = GHRateLimit.Unknown();
+            // GitHub Enterprise doesn't have the rate_limit endpoint
```
Comment (timja) [inline src/main/java/org/kohsuke/github/GitHubClient.java:227]: I don’t think this statement is right anymore at least on recent versions from reading the docs,

My understanding is that it is available but there’s a global flag for turning it off or on.

Having it off means that it will return a 404

Comment (bitwiseman) [inline src/main/java/org/kohsuke/github/GitHubClient.java:227]:
```suggestion
            // For some versions of GitHub Enterprise, the rate_limit endpoint returns a 404.
```
