### PR TITLE
Accept 429 response codes as an indication of the secondary rate limit being exceeded

### LINKED ISSUE #1805: Handle rate limit errors appropriately :: GitHub Doesn't always send `Retry-After` header for secondary rate limits
**Describe the bug**
The [GitHub Docs](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28) now say:

> Otherwise, wait for at least one minute before retrying. If your request continues to fail due to a secondary rate limit, wait for an exponentially increasing amount of time between retries, and throw an error after a specific number of retries.

There's also a whole complex list [About secondary rate limits](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits). 

**To Reproduce**
Reach Secondary Quota Limits:
* At least 5 GET rps
* At least 1.4 POST rps
* Run until you get Secondary Quota Error: 

> "You have exceeded a secondary rate limit and have been temporarily blocked from content creation. Please retry your request again later"

**Expected behavior**
GitHub SHOULD return a retry-after header but it does not. So I've thought of a couple ideas:
1. Make the GitHubConnectorResponseErrorHandler.isError() method public down the stack so users (me) can customize the behavior. 
2. Update the private GitHubAbuseLimitHandler.isError() logic to handle no `Retry-After` header as described in the [GitHub Docs](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28). This may not be ideal because note everyone is running a long-running project like I am so they may not be OK with a default 1-minute sleep before throwing a RetryRequestException.  

**Desktop (please complete the following information):**
 - OS: MacOS
 - JVM: Eclipse Temurin 21
 - Spring-Boot 3.2.3

**Additional context**
BTW I'm using a GitHub Enterprise User Account accessing GH Enterprise resources so maybe that's why there's no `Retry-After` header?

Another Idea is related to `rateLimitChecker.checkRateLimit(this, request.rateLimitTarget());` inside the GitHubClient.sendRequest method. If it could also pass the GitHub request instead of just the rateLimitTarget then I could configure more smart ratelimit checker which tracks api calls of differing "points" to reduce throughput of the 'create content' requests which GitHub limits much more heavily than Read requests.

### LINKED ISSUE #1842: Github Repository Search resulting in Secondary Rate Limit
**Describe the bug**
Getting the below error when searching for repositories with a keyword that returns a lot of repositories in the result. My usecase can be fulfilled by just getting say top 50 results, but I do not see any way to do that on the server side but only post getting the results.
```
org.kohsuke.github.HttpException: {
  "documentation_url": "https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits",
  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID ...."
}
```

I was trying the search for repositories within my org and keywords that matched even around 850 repositories were hitting this rate limit. The github documentation quotes a much larger number.

I even tried the `in:name` and `in:displayName` within the query but even that did not seem to help.

**To Reproduce**
```
new GitHubBuilder().withAppInstallationToken(token).build()
                .searchRepositories()
                .org(orgName)
                .q(repoName)
                .list();
```
Just pass in a repo name like "test" or something that results in a lot of repository results in the above code.

**Expected Behaviour**
It should return the repositories or else provide a clear reason of why the error. Or else there should be a way to limit the search results on the GitHub side itself. 

**Additional Info**
Version: org.kohsuke:github-api:1.316

### PR DESCRIPTION
**Pull request by holly-cummins**
Resolves #1842.
Resolves #1805. 

# Description

If a user uses this library to drive the GitHub API hard, there will quite often be failures caused by secondary rate limits being breached (#1842 and #1805). There’s been some discussion of headers on #1842, and also of pluggable 'handle the rate limit' modules, but I think there’s a more fundamental problem with the handling of rate limits. (The good news is this means there's a simpler solution, too.)

The `AbuseLimitHandler` checks for a rate limit violation by looking for a 403 header and some headers:  

```
@Override
boolean isError(@Nonnull GitHubConnectorResponse connectorResponse) {
    return isForbidden(connectorResponse) && hasRetryOrLimitHeader(connectorResponse);
}
```

`HTTP_FORBIDDEN` is a 403. The [GitHub docs](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#exceeding-the-rate-limit) indicate that limits from GitHub are signalled with either 403 or `TOO_MANY_REQUESTS` responses (429). In my experience, I've only seen 429s.

### What about headers? 

The GitHub docs docs suggest that any headers are optional, and that in the absence of headers the code should just wait a minute (which, luckily, is what the current implementation already does):

>  If the retry-after response header is present, you should not retry your request until after that many seconds has elapsed. If the x-ratelimit-remaining header is 0, you should not retry your request until after the time, in UTC epoch seconds, specified by the x-ratelimit-reset header. Otherwise, wait for at least one minute before retrying. If your request continues to fail due to a secondary rate limit, wait for an exponentially increasing amount of time between retries, and throw an error after a specific number of retries.

Based on these docs, I think it's sufficient to count a 429 as a rate limit response, even if headers are missing. Semantically, a 429 is an indication of an abuse detection/rate limit scenario, and should be handled as such.

### What about the rate limit handler?

`GitHubRateLimitHandler` also requires a 403 to 'count' a response as rate limited:

```
@Override
boolean isError(@NotNull GitHubConnectorResponse connectorResponse) throws IOException {
connectorResponse.statusCode() == HttpURLConnection.HTTP_FORBIDDEN
            && "0".equals(connectorResponse.header("X-RateLimit-Remaining"));
```

I didn't update this one, since the secondary rate limit checks are now correctly being handled on the abuse path with my changes. It might be worth updating it, or also even considering whether the distinction between the abuse and rate limit paths is so fuzzy that having both is just maintenance overhead. But that’s a different discussion. 

# Before submitting a PR:

- [ X] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ X] Add JavaDocs and other comments explaining the behavior. 
- [ ] When adding or updating methods that fetch entities, add `@link` JavaDoc entries to the relevant documentation on https://docs.github.com/en/rest . 
- [ ] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [ ] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [ X] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [X] Fill in the "Description" above with clear summary of the changes. This includes:
  - [X ] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [ X] Provide links to relevant documentation on https://docs.github.com/en/rest where possible. If not including links, explain why not.
- [X ] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [X] Enable "Allow edits from maintainers".

### CODE REVIEW

File: src/main/java/org/kohsuke/github/GitHubAbuseLimitHandler.java [hunk 1]
```diff
@@ -29,7 +29,19 @@ public abstract class GitHubAbuseLimitHandler extends GitHubConnectorResponseErr
      */
     @Override
     boolean isError(@Nonnull GitHubConnectorResponse connectorResponse) {
-        return isForbidden(connectorResponse) && hasRetryOrLimitHeader(connectorResponse);
+        return isTooManyRequests(connectorResponse)
+                || (isForbidden(connectorResponse) && hasRetryOrLimitHeader(connectorResponse));
+    }
+
+    /**
+     * Checks if the response status code is TOO_MANY_REQUESTS (403).
```
Comment (bitwiseman) [inline src/main/java/org/kohsuke/github/GitHubAbuseLimitHandler.java:37]:
```suggestion
     * Checks if the response status code is TOO_MANY_REQUESTS (429).
```

File: src/main/java/org/kohsuke/github/AbuseLimitHandler.java [hunk 2]
```diff
@@ -89,7 +89,7 @@ public void onError(IOException e, HttpURLConnection uc) throws IOException {
         private long parseWaitTime(HttpURLConnection uc) {
             String v = uc.getHeaderField("Retry-After");
             if (v == null)
-                return 60 * 1000; // can't tell, return 1 min
+                return 61 * 1000; // can't tell, return 1 min plus 1 second for luck
```
Comment (bitwiseman) [inline src/main/java/org/kohsuke/github/AbuseLimitHandler.java:92]: Is there a functional reason for this?

**Review by bitwiseman — CHANGES_REQUESTED** [review]
This is a definite improvement.  

It still needs tests. Look at the existing abuse limit tests, which use manually constructed test data. Maybe just add one more step to the existing test rather than adding a whole new test. Up to you.

File: src/main/java/org/kohsuke/github/AbuseLimitHandler.java (hunk 2 above)
Comment (holly-cummins) [reply src/main/java/org/kohsuke/github/AbuseLimitHandler.java:92]: The [GitHub docs](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#exceeding-the-rate-limit) say "Otherwise, wait for at least one minute before retrying." I never know if the check is `< 60s` or `<=60s`, but it seems like waiting something that is unambiguously more than a minute is safest.

**Comment by holly-cummins** [comment]
Oh good, I'm glad it looks sensible. I've added some tests and squashed.

File: src/main/java/org/kohsuke/github/AbuseLimitHandler.java (hunk 2 above)
Comment (bitwiseman) [inline src/main/java/org/kohsuke/github/AbuseLimitHandler.java:92]:
```suggestion
                // can't tell, wait for unambiguously over one minute per GitHub guidance
                return 61 * 1000;
```

**Review by bitwiseman — APPROVED** [review]

**Comment by bitwiseman** [comment]
Please don't squash/force-push.  We can squash when merging the PR.

**Review by bitwiseman — CHANGES_REQUESTED** [review]
Test failure needs fixing.

**Comment by holly-cummins** [comment]
> Test failure needs fixing.

Oops, sorry about that. And noted about the squashing - different orgs have different requirements, so I have a squash habit, but I'll keep the commits separate. I agree it does make subsequent reviews easier!

File: src/test/java/org/kohsuke/github/AbuseLimitHandlerTest.java [hunk 3]
```diff
@@ -412,7 +412,6 @@ public void onError(IOException e, HttpURLConnection uc) throws IOException {
                         assertThat(uc.getContentType(), equalTo("application/json; charset=utf-8"));
                         assertThat(uc.getContentLength(), equalTo(-1));
                         assertThat(uc.getHeaderFields(), instanceOf(Map.class));
-                        assertThat(uc.getHeaderFields().size(), Matchers.greaterThan(25));
```
Comment (bitwiseman) [inline src/test/java/org/kohsuke/github/AbuseLimitHandlerTest.java]: I wonder why I even had this in there...

Comment (holly-cummins) [reply src/test/java/org/kohsuke/github/AbuseLimitHandlerTest.java]: Yeah, I think there's an opportunity to make some of the tests a bit more concise and flexible without losing the important sense checks about the mocks' behaviour or the validation of the actual code ... but I didn't want to change too much existing code in an unrelated PR. But I perhaps should have been a bit more conservative about how much I copy-pasted.

**Comment by holly-cummins** [comment]
The CI's failing because I didn't have enough coverage, even with the new test. To get the `parseWaitTime` method to be testable, I had to do a bit of refactoring to make it visible to the test code. I also added a new test to cover both paths, and then I realised that the original code could fail with a `NumberFormatException`, because `Retry-After` can [be a date](https://www.rfc-editor.org/rfc/rfc9110#field.retry-after). So I added new code and tests to handle that case. I also did a bit of refactoring of the test code and removing assertions about the mock that I was pretty sure we definitely didn't care about.

**Review by bitwiseman — APPROVED** [review]
Sorry for the slow response cycle.

File: src/main/java/org/kohsuke/github/AbuseLimitHandler.java [hunk 4]
```diff
@@ -105,4 +101,26 @@ public void onError(IOException e, HttpURLConnection uc) throws IOException {
             throw e;
         }
     };
+
+    /*
+     * Exposed for testability. Given an http response, find the retry-after header field
+     * and parse it as either a number or a date (the spec allows both).
+     * If no header is found, wait for a reasonably amount of time.
+     */
```
Comment (bitwiseman) [inline src/main/java/org/kohsuke/github/AbuseLimitHandler.java:109]:
```suggestion
    /*
     * Exposed for testability. Given an http response, find the retry-after header field and parse it as either a
     * number or a date (the spec allows both). If no header is found, wait for a reasonably amount of time.
     */
```

File: src/test/java/org/kohsuke/github/AbuseLimitHandlerTest.java [hunk 5]
```diff
@@ -349,16 +342,191 @@ public void onError(IOException e, HttpURLConnection uc) throws IOException {
...
+            getTempRepository();
+            fail();
+        } catch (Exception e) {
+            assertThat(e, instanceOf(HttpException.class));
+            assertThat(e.getMessage(), equalTo("Abuse limit reached"));
+        }
+        assertThat(mockGitHub.getRequestCount(), equalTo(2));
+    }
+
+    @Test
```
Comment (bitwiseman) [inline src/test/java/org/kohsuke/github/AbuseLimitHandlerTest.java:441]:
```suggestion
    /**
     * Tests the behavior of the GitHub API client when the abuse limit handler with a date retry.
     *
     * @throws Exception
     *             if any error occurs during the test execution.
     */
    @Test
```

File: src/test/java/org/kohsuke/github/AbuseLimitHandlerTest.java [hunk 6]
```diff
@@ -349,16 +342,191 @@ public void onError(IOException e, HttpURLConnection uc) throws IOException {
...
```
Comment (bitwiseman) [inline src/test/java/org/kohsuke/github/AbuseLimitHandlerTest.java:493]:
```suggestion
    /**
     * Tests the behavior of the GitHub API client when the abuse limit handler with a no retry after header.
     *
     * @throws Exception
     *             if any error occurs during the test execution.
     */
    @Test
```

File: src/main/java/org/kohsuke/github/AbuseLimitHandler.java [hunk 7]
```diff
@@ -105,4 +101,22 @@ public void onError(IOException e, HttpURLConnection uc) throws IOException {
...
+            // can't tell, wait for unambiguously over one minute per GitHub guidance
+            return 61 * 1000;
+        }
+
+        try {
+            return Math.max(1000, Long.parseLong(v) * 1000);
+        } catch (NumberFormatException nfe) {
+            // The retry-after header could be a number in seconds, or an http-date
+            ZonedDateTime zdt = ZonedDateTime.parse(v, DateTimeFormatter.RFC_1123_DATE_TIME);
+            return ChronoUnit.MILLIS.between(ZonedDateTime.now(), zdt);
```
[the remark this answers is not in the document]
Comment (holly-cummins) [reply src/main/java/org/kohsuke/github/AbuseLimitHandler.java:121]: Thanks! (And thanks for explaining about the diff to the response time, that makes a lot of sense.)

[the remark this answers is not in the document]
Comment (bitwiseman) [reply src/main/java/org/kohsuke/github/AbuseLimitHandler.java:121]: Sure thing.  If you have time to circle back and address #1909 , that would be awesome.  Thanks for the great contribution!
