### PR TITLE
Make root field transient in all classes

### LINKED ISSUE #996: Failed to convert JsonString.
How to convert an issue object to String? An error occurs during each conversion.

### PR DESCRIPTION
**Pull request by bitwiseman**
# Description 
The GitHub field present in many objects in this library should never be serialized. 

This change doesn't perform the additional work of making all access to `root` through got through methods. That will be done in a future change. 

Fixes #996

@lwx979458 

# Before submitting a PR:
We love getting PRs, but we hate asking people for the same basic changes every time. 

- [x] Push your changes to a branch other than `master`. Create your PR from that branch.    
- [x] Add JavaDocs and other comments
- [ ] Write tests that run and pass in CI. See [CONTRIBUTING.md](CONTRIBUTING.md) for details on how to capture snapshot data.
- [x] Run `mvn clean compile` locally. This may reformat your code, commit those changes.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.

# When creating a PR: 

- [x] Fill in the "Description" above. 
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

**Review by timja — APPROVED** [review]

File: src/main/java/org/kohsuke/github/GitHub.java [hunk 1]
```diff
@@ -1208,26 +1208,34 @@ public Reader renderMarkdown(String text) throws IOException {
     }
 
     /**
-     * Do not use this method. This method will be removed and should never have been needed in the first place.
+     * Gets an {@link ObjectWriter} that can be used to convert data objects in this library to JSON.
+     *
+     * If you must convert data object in this library to JSON, the {@link ObjectWriter} returned by this method is the
+     * only support way of doing so. This {@link ObjectWriter} can be used to convert any library data object to JSON
```
Comment (timja) [inline src/main/java/org/kohsuke/github/GitHub.java:1214]:
```suggestion
     * only supported way of doing so. This {@link ObjectWriter} can be used to convert any library data object to JSON
```

**Review by timja — COMMENTED** [review]
typo
