### PR TITLE
Return all files from a commit

### LINKED ISSUE #1669: GHCommit.getFiles() limited to 300 files, does not support pagination
**Describe the bug**
https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#get-a-commit

> Note: If there are more than 300 files in the commit diff, the response will include pagination link headers for the remaining files, up to a limit of 3000 files. Each page contains the static commit information, and the only changes are to the file listing.

Except `hub4j` doesn't support pagination at this time: 
https://github.com/hub4j/github-api/blob/9801b86b8aff903aaee4b7b0983a616ee646db0d/src/main/java/org/kohsuke/github/GHCommit.java#L418-L421

**To Reproduce**
1. Use `GHCommit.getFiles()` on a commit with more than 300 files changed. 

**Expected behavior**
Suggest deprecating `getFiles()` and adding a `listFile()` that returns a [`PagedIterable`](https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/PagedIterable.java).  However, I think that `PagedIterable` will need to be backed by a custom class similar to  [`GHWorkflowsIterable`](https://github.com/hub4j/github-api/blob/main/src/main/java/org/kohsuke/github/GHWorkflowsIterable.java) with the `GHCommit` as the container.  It's going to take some trial-and-error to figure out how this works.

### PR DESCRIPTION
**Pull request by frink182**
# Description

Fixes #1669
If there are more than 300 files in the commit diff, the GitHub API response will include pagination link headers for the remaining files, up to a limit of 3000 files. Each page contains the static commit information, and the only changes are to the file listing. This PR adds `GHCommit.listFiles()` which returns the list of files in a commit via paginated responses. It deprecates the previous method to get the files: `GHCommit.getFiles()`.

The PR also populates the `message` in a `GHCommit` which was previously null.

# Before submitting a PR:

- [x] Changes must not break binary backwards compatibility. If you are unclear on how to make the change you think is needed while maintaining backward compatibility, [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Add JavaDocs and other comments explaining the behavior. 
- [x] When adding or updating methods that fetch entities, add `@link` JavaDoc entries to the relevant documentation on https://docs.github.com/en/rest . 
- [x] Add tests that cover any added or changed code. This generally requires capturing snapshot test data. See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
- [x] Run `mvn -D enable-ci clean install site` locally. If this command doesn't succeed, your change will not pass CI.
- [x] Push your changes to a branch other than `main`. You will create your PR from that branch.

# When creating a PR: 

- [x] Fill in the "Description" above with clear summary of the changes. This includes:
  - [x] If this PR fixes one or more issues, include "Fixes #<issue number>" lines for each issue. 
  - [x] Provide links to relevant documentation on https://docs.github.com/en/rest where possible. If not including links, explain why not.
- [x] All lines of new code should be covered by tests as reported by code coverage. Any lines that are not covered must have PR comments explaining why they cannot be covered. For example, "Reaching this particular exception is hard and is not a particular common scenario."
- [x] Enable "Allow edits from maintainers".

### CODE REVIEW

File: src/main/java/org/kohsuke/github/GHCommitIterable.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+     *
+     * @param owner
+     *            the owner
+     * @param sha
+     *            the SHA of the commit
+     */
+    public GHCommitIterable(GHRepository owner, String sha) {
+        this.owner = owner;
+        this.sha = sha;
+    }
```
Comment (bitwiseman) [inline src/main/java/org/kohsuke/github/GHCommitIterable.java:29]: Need to add an internal constructor for this path.
```suggestion
    public GHCommitIterable(GHRepository owner, String sha, List<File> files) {
        this.owner = owner;
        this.sha = sha;
        this.result = new GHCommitFilesPage(files != null ? files.toArray(GHCommit.File[]::new) : new GHCommit.File[0]);
    }
```

File: src/main/java/org/kohsuke/github/GHCommitIterable.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+    @Nonnull
+    @Override
+    public PagedIterator<GHCommit.File> _iterator(int pageSize) {
+
+        GitHubRequest request = owner.root().createRequest().withUrlPath(owner.getApiTailUrl("commits/" + sha)).build();
+
+        return new PagedIterator<>(
+                adapt(GitHubPageIterator.create(owner.root().getClient(), GHCommitFilesPage.class, request, pageSize)),
+                null);
+    }
```
Comment (bitwiseman) [inline src/main/java/org/kohsuke/github/GHCommitIterable.java:47]: Move the logic that controls which iterating strategy to here. 
I haven't tried to compile this yet, so you may need to make some tweaks, but the basic idea should be there. 

You may or may not need to rerecord your test data. I think not....

```suggestion
    public PagedIterator<GHCommit.File> _iterator(int pageSize) {
        Iterator<GHCommit.File[]> pageIterator;
        if (results.getFiles().length() < GHCommit.GH_FILE_LIMIT_PER_COMMIT_PAGE) {
            // create a page iterator that only provides one page
            pageIterator = Collections.singleton(results.getFiles()).iterator();
        } else {
            // page size is controlled by the server for this iterator, do not allow it to be set by the caller
            pageSize = 0;

            GitHubRequest request = owner.root().createRequest().withUrlPath(owner.getApiTailUrl("commits/" + sha)).build();

           pageIterator = adapt(
                    GitHubPageIterator.create(owner.root().getClient(), GHCommitFilesPage.class, request, pageSize));
        }
        return new PagedIterator<>(pageIterator, null);
    }
```

**Review by bitwiseman — CHANGES_REQUESTED** [review]
This is basically all one big change suggestion to make `listFiles()` return a `PagedIterable`.  
Other than that, this PR looks great!  Well tested.

**Comment by frink182** [comment]
@bitwiseman I've made the suggested changes, let me know how it looks now. Thanks

**Review by bitwiseman — APPROVED** [review]
